# -*- coding: utf-8 -*-
"""fossil_free_lab_sorting.ipynb
Automatically generated by Colab.
"""

import pandas as pd
import matplotlib.pyplot as plt

# Code generated / adjusted with prompts to Claude 3.5

# Import files from fffreestanford github
results_df = pd.read_csv('results_df.csv')


# Pie chart - percentage of PIs with FF funding
total_pis = len(projects['Principal Investigator'].unique())
ff_funded_pis = len(results_df)
ff_funded_percent = (ff_funded_pis / total_pis * 100)
print(f'Total PIs: {total_pis}')
print(f'PIs with FF Funding: {ff_funded_pis}')
print(f'Percentage of PIs with FF Funding: {ff_funded_percent:.1f}%)')

# Create pie chart
non_ff_percent = 100 - ff_funded_percent

labels = ['PIs with FF Funding', 'PIs without FF Funding']
sizes = [ff_funded_percent, non_ff_percent]
colors = ['#ff9999', '#66b3ff']

plt.figure(figsize=(4, 4))
plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%')
plt.title('Distribution of PIs with Fossil Fuel Funding')
plt.axis('equal')
plt.show()

# Calculate funding by department
dept_funding = {}

awarded_projects = projects[projects['Project Status'] == 'Awarded']

# Calculate FF and total funding for each department
for idx, project in awarded_projects.iterrows():
    dept = project['Department']
    amount = float(project['Funded'].replace('$', '').replace(',', ''))

    if dept not in dept_funding:
        dept_funding[dept] = {'ff': 0, 'total': 0}

    dept_funding[dept]['total'] += amount

    # Check if any sponsor column matches FF companies
    if matches[idx]:
        dept_funding[dept]['ff'] += amount

# Calculate percentages and create dataframe
dept_stats = []
for dept, amounts in dept_funding.items():
    ff_pct = (amounts['ff'] / amounts['total'] * 100) if amounts['total'] > 0 else 0
    dept_stats.append({
        'Department': dept,
        'FF Funding': amounts['ff'],
        'Total Funding': amounts['total'],
        'FF Percentage': ff_pct
    })

dept_df = pd.DataFrame(dept_stats)
dept_df = dept_df.sort_values('FF Funding', ascending=False)
n_depts = 6
top_depts = dept_df.head(n_depts)

# Print overall statistics
total_funding = dept_df['Total Funding'].sum()
ff_funding = dept_df['FF Funding'].sum()
ff_funding_pct = (ff_funding / total_funding * 100) if total_funding > 0 else 0

print(f"\nFunding Analysis:")
print(f"Total Funding: ${total_funding:,.2f}")
print(f"Fossil Fuel Funding: ${ff_funding:,.2f}")
print(f"Percentage from Fossil Fuel Sources: {ff_funding_pct:.1f}%")

# Create subplot with overall pie chart and top 5 departments bar chart
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Overall pie chart
labels = ['FF Funding', 'Other Funding']
sizes = [ff_funding_pct, 100-ff_funding_pct]
colors = ['#ff9999', '#66b3ff']

ax1.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%')
ax1.set_title('Stanford-Wide Sponsored Research Funds')

# Top 5 departments bar chart
departments = top_depts['Department']
percentages = top_depts['FF Percentage']

ax2.barh(departments, percentages, color='#ff9999')
ax2.set_xlabel('FF Funding Percentage')
ax2.set_title(f'Breakdown by Department')

plt.tight_layout()
plt.show()

## TODO:
## -- add faculty who are indirectly accepting FF funds through Industrial Affiliate Programs
## -- add a year-by-year breakdown: is the number of faculty accepting fossil fuel money increasing,
##    decreasing, or staying the same over time? I.e. is Stanford getting better or worse?

"""# CONGO"""

# Find matches where a Congo company is in the sponsor column
matches = projects['Sponsor/Party'].apply(lambda x: any(company in str(x) for company in congo_companies))

# Calculate Congo funding percentage per PI
pi_stats = []
for pi in projects['Principal Investigator'].unique():
    pi_projects = projects[(projects['Principal Investigator'] == pi) & (projects['Project Status'].isin(['Awarded', 'Approved']))]
    total_projects = len(pi_projects)

    # Count Congo funded projects using matches
    congo_funded = matches[pi_projects.index].sum()

    congo_percentage = (congo_funded / total_projects * 100) if total_projects > 0 else 0
    pi_stats.append({
        'PI': pi,
        'Total Projects': total_projects,
        'Congo Funded Projects': congo_funded,
        'Congo Funding Percentage': round(congo_percentage, 1)
    })

# Create and display results dataframe
results_df = pd.DataFrame(pi_stats)
results_df = results_df[results_df['Congo Funded Projects'] > 0]
results_df = results_df.sort_values('Congo Funding Percentage', ascending=False)
results_df = results_df.reset_index(drop=True)
print("\nPrincipal Investigator Congo Funding Statistics for Awarded Projects:")
print(results_df[['PI','Congo Funded Projects','Congo Funding Percentage']].head(15))
