# -*- coding: utf-8 -*-
"""fossil_free_lab_sorting.ipynb
Automatically generated by Colab.
"""

import pandas as pd
import matplotlib.pyplot as plt

# Code generated / adjusted with prompts to Claude 3.5

# Import files from fffreestanford github

results_df = pd.read_csv('results_df.csv')
projects = pd.read_csv('Project_List_Report_2005_2024.csv')
congo_companies = pd.read_csv('congo_sponsors.csv')
fossil_companies = pd.red_csv('fossil_sponsors.csv')

# Pie chart - percentage of PIs with FF funding
total_pis = len(projects['Principal Investigator'].unique())
ff_funded_pis = len(results_df)
ff_funded_percent = (ff_funded_pis / total_pis * 100)
print(f'Total PIs: {total_pis}')
print(f'PIs with FF Funding: {ff_funded_pis}')
print(f'Percentage of PIs with FF Funding: {ff_funded_percent:.1f}%)')

# Calculate funding by department
dept_funding = {}

awarded_projects = projects[projects['Project Status'] == 'Awarded']

# Calculate FF and total funding for each department
for idx, project in awarded_projects.iterrows():
    dept = project['Department']
    amount = float(project['Funded'].replace('$', '').replace(',', ''))

    if dept not in dept_funding:
        dept_funding[dept] = {'ff': 0, 'total': 0}

    dept_funding[dept]['total'] += amount

    # Check if any sponsor column matches FF companies
    if matches[idx]:
        dept_funding[dept]['ff'] += amount

# Calculate percentages and create dataframe
dept_stats = []
for dept, amounts in dept_funding.items():
    ff_pct = (amounts['ff'] / amounts['total'] * 100) if amounts['total'] > 0 else 0
    dept_stats.append({
        'Department': dept,
        'FF Funding': amounts['ff'],
        'Total Funding': amounts['total'],
        'FF Percentage': ff_pct
    })

dept_df = pd.DataFrame(dept_stats)
dept_df = dept_df.sort_values('FF Funding', ascending=False)
n_depts = 6
top_depts = dept_df.head(n_depts)

# Print overall statistics
total_funding = dept_df['Total Funding'].sum()
ff_funding = dept_df['FF Funding'].sum()
ff_funding_pct = (ff_funding / total_funding * 100) if total_funding > 0 else 0

print(f"\nFunding Analysis:")
print(f"Total Funding: ${total_funding:,.2f}")
print(f"Fossil Fuel Funding: ${ff_funding:,.2f}")
print(f"Percentage from Fossil Fuel Sources: {ff_funding_pct:.1f}%")

# Create subplot with overall pie chart and top 5 departments bar chart
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Overall pie chart
labels = ['FF Funding', 'Other Funding']
sizes = [ff_funding_pct, 100-ff_funding_pct]
colors = ['#ff9999', '#66b3ff']

ax1.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%')
ax1.set_title('Stanford-Wide Sponsored Research Funds')

# Top 5 departments bar chart
departments = top_depts['Department']
percentages = top_depts['FF Percentage']

ax2.barh(departments, percentages, color='#ff9999')
ax2.set_xlabel('FF Funding Percentage')
ax2.set_title(f'Breakdown by Department')

plt.tight_layout()
plt.show()

## TODO:
## -- add faculty who are indirectly accepting FF funds through Industrial Affiliate Programs
## -- add a year-by-year breakdown: is the number of faculty accepting fossil fuel money increasing,
##    decreasing, or staying the same over time? I.e. is Stanford getting better or worse?
